// Last week's diagnosis snapshots — used by loadTutorData to compute
// the weekly delta block on the Lumi page. Each snapshot was captured
// BEFORE the current cache was overwritten by the Friday refresh, so
// it represents "last Friday's report" for delta purposes.
//
// AUTOGENERATED by scripts/run-weekly-lumi.ts. Do not hand-edit — the
// next weekly refresh will overwrite the file. Add new (kid × subject)
// entries by running the refresh; the index regenerates from the
// .lastweek files on disk.

import adrielEnglishLW from "./tutor-cache/unified-diagnosis-adriel-english.lastweek.gemini-cache.json";
import al4EnglishLW from "./tutor-cache/unified-diagnosis-al4-english.lastweek.gemini-cache.json";
import al4ScienceLW from "./tutor-cache/unified-diagnosis-al4-science.lastweek.gemini-cache.json";
import alexaGohScienceLW from "./tutor-cache/unified-diagnosis-alexa-goh-science.lastweek.gemini-cache.json";
import allisonteoEnglishLW from "./tutor-cache/unified-diagnosis-allisonteo-english.lastweek.gemini-cache.json";
import amberamberteoMathLW from "./tutor-cache/unified-diagnosis-amberamberteo-math.lastweek.gemini-cache.json";
import amberamberteoScienceLW from "./tutor-cache/unified-diagnosis-amberamberteo-science.lastweek.gemini-cache.json";
import andreaEnglishLW from "./tutor-cache/unified-diagnosis-andrea-english.lastweek.gemini-cache.json";
import angyunshanarielEnglishLW from "./tutor-cache/unified-diagnosis-angyunshanariel-english.lastweek.gemini-cache.json";
import audreyEnglishLW from "./tutor-cache/unified-diagnosis-audrey-english.lastweek.gemini-cache.json";
import benjaminOngMathLW from "./tutor-cache/unified-diagnosis-benjamin-ong-math.lastweek.gemini-cache.json";
import benjaminOngScienceLW from "./tutor-cache/unified-diagnosis-benjamin-ong-science.lastweek.gemini-cache.json";
import calebEnglishLW from "./tutor-cache/unified-diagnosis-caleb-english.lastweek.gemini-cache.json";
import calebScienceLW from "./tutor-cache/unified-diagnosis-caleb-science.lastweek.gemini-cache.json";
import claraEnglishLW from "./tutor-cache/unified-diagnosis-clara-english.lastweek.gemini-cache.json";
import davidLimEnglishLW from "./tutor-cache/unified-diagnosis-david-lim-english.lastweek.gemini-cache.json";
import davidLimMathLW from "./tutor-cache/unified-diagnosis-david-lim-math.lastweek.gemini-cache.json";
import davidLimScienceLW from "./tutor-cache/unified-diagnosis-david-lim-science.lastweek.gemini-cache.json";
import drewieScienceLW from "./tutor-cache/unified-diagnosis-drewie-science.lastweek.gemini-cache.json";
import egEnglishLW from "./tutor-cache/unified-diagnosis-eg-english.lastweek.gemini-cache.json";
import el44EnglishLW from "./tutor-cache/unified-diagnosis-el44-english.lastweek.gemini-cache.json";
import elijahScienceLW from "./tutor-cache/unified-diagnosis-elijah-science.lastweek.gemini-cache.json";
import emilyLimEnglishLW from "./tutor-cache/unified-diagnosis-emily-lim-english.lastweek.gemini-cache.json";
import emilyLimMathLW from "./tutor-cache/unified-diagnosis-emily-lim-math.lastweek.gemini-cache.json";
import emilyLimScienceLW from "./tutor-cache/unified-diagnosis-emily-lim-science.lastweek.gemini-cache.json";
import enxinScienceLW from "./tutor-cache/unified-diagnosis-enxin-science.lastweek.gemini-cache.json";
import evangMathLW from "./tutor-cache/unified-diagnosis-evang-math.lastweek.gemini-cache.json";
import fightingseoMathLW from "./tutor-cache/unified-diagnosis-fightingseo-math.lastweek.gemini-cache.json";
import hongjun23ScienceLW from "./tutor-cache/unified-diagnosis-hongjun23-science.lastweek.gemini-cache.json";
import hooperMathLW from "./tutor-cache/unified-diagnosis-hooper-math.lastweek.gemini-cache.json";
import ijEnglishLW from "./tutor-cache/unified-diagnosis-ij-english.lastweek.gemini-cache.json";
import ijScienceLW from "./tutor-cache/unified-diagnosis-ij-science.lastweek.gemini-cache.json";
import jayronLohYiHengStudentsEduSgMathLW from "./tutor-cache/unified-diagnosis-jayron-loh-yi-heng-students-edu-sg-math.lastweek.gemini-cache.json";
import jeremiahsyEnglishLW from "./tutor-cache/unified-diagnosis-jeremiahsy-english.lastweek.gemini-cache.json";
import jeremiahsyMathLW from "./tutor-cache/unified-diagnosis-jeremiahsy-math.lastweek.gemini-cache.json";
import jeremiahsyScienceLW from "./tutor-cache/unified-diagnosis-jeremiahsy-science.lastweek.gemini-cache.json";
import jeron16EnglishLW from "./tutor-cache/unified-diagnosis-jeron16-english.lastweek.gemini-cache.json";
import jonTanEnglishLW from "./tutor-cache/unified-diagnosis-jon-tan-english.lastweek.gemini-cache.json";
import jonTanMathLW from "./tutor-cache/unified-diagnosis-jon-tan-math.lastweek.gemini-cache.json";
import joylynnEnglishLW from "./tutor-cache/unified-diagnosis-joylynn-english.lastweek.gemini-cache.json";
import kaiyangngggEnglishLW from "./tutor-cache/unified-diagnosis-kaiyangnggg-english.lastweek.gemini-cache.json";
import kaiyangngggMathLW from "./tutor-cache/unified-diagnosis-kaiyangnggg-math.lastweek.gemini-cache.json";
import kaiyangngggScienceLW from "./tutor-cache/unified-diagnosis-kaiyangnggg-science.lastweek.gemini-cache.json";
import kaydenEnglishLW from "./tutor-cache/unified-diagnosis-kayden-english.lastweek.gemini-cache.json";
import lohxy2014EnglishLW from "./tutor-cache/unified-diagnosis-lohxy2014-english.lastweek.gemini-cache.json";
import lohxy2014MathLW from "./tutor-cache/unified-diagnosis-lohxy2014-math.lastweek.gemini-cache.json";
import lohzrP4EnglishLW from "./tutor-cache/unified-diagnosis-lohzr-p4-english.lastweek.gemini-cache.json";
import lohzrP4ScienceLW from "./tutor-cache/unified-diagnosis-lohzr-p4-science.lastweek.gemini-cache.json";
import mahdi12EnglishLW from "./tutor-cache/unified-diagnosis-mahdi12-english.lastweek.gemini-cache.json";
import markLimEnglishLW from "./tutor-cache/unified-diagnosis-mark-lim-english.lastweek.gemini-cache.json";
import markLimMathLW from "./tutor-cache/unified-diagnosis-mark-lim-math.lastweek.gemini-cache.json";
import markLimScienceLW from "./tutor-cache/unified-diagnosis-mark-lim-science.lastweek.gemini-cache.json";
import meryllEnglishLW from "./tutor-cache/unified-diagnosis-meryll-english.lastweek.gemini-cache.json";
import natashatsaiEnglishLW from "./tutor-cache/unified-diagnosis-natashatsai-english.lastweek.gemini-cache.json";
import naurahumairaEnglishLW from "./tutor-cache/unified-diagnosis-naurahumaira-english.lastweek.gemini-cache.json";
import rizqiEnglishLW from "./tutor-cache/unified-diagnosis-rizqi-english.lastweek.gemini-cache.json";
import ruthieScienceLW from "./tutor-cache/unified-diagnosis-ruthie-science.lastweek.gemini-cache.json";
import saarah1EnglishLW from "./tutor-cache/unified-diagnosis-saarah1-english.lastweek.gemini-cache.json";
import shadowDemonEnglishLW from "./tutor-cache/unified-diagnosis-shadow-demon-english.lastweek.gemini-cache.json";
import shayaneEnglishLW from "./tutor-cache/unified-diagnosis-shayane-english.lastweek.gemini-cache.json";
import shayaneScienceLW from "./tutor-cache/unified-diagnosis-shayane-science.lastweek.gemini-cache.json";
import student66666EnglishLW from "./tutor-cache/unified-diagnosis-student66666-english.lastweek.gemini-cache.json";
import tylerngEnglishLW from "./tutor-cache/unified-diagnosis-tylerng-english.lastweek.gemini-cache.json";
import tylerngMathLW from "./tutor-cache/unified-diagnosis-tylerng-math.lastweek.gemini-cache.json";
import umarhScienceLW from "./tutor-cache/unified-diagnosis-umarh-science.lastweek.gemini-cache.json";
import umarmEnglishLW from "./tutor-cache/unified-diagnosis-umarm-english.lastweek.gemini-cache.json";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const LUMI_LASTWEEK_CACHE: Record<string, any> = {
  "adriel:english": adrielEnglishLW,
  "al4:english": al4EnglishLW,
  "al4:science": al4ScienceLW,
  "alexa-goh:science": alexaGohScienceLW,
  "allisonteo:english": allisonteoEnglishLW,
  "amberamberteo:math": amberamberteoMathLW,
  "amberamberteo:science": amberamberteoScienceLW,
  "andrea:english": andreaEnglishLW,
  "angyunshanariel:english": angyunshanarielEnglishLW,
  "audrey:english": audreyEnglishLW,
  "benjamin-ong:math": benjaminOngMathLW,
  "benjamin-ong:science": benjaminOngScienceLW,
  "caleb:english": calebEnglishLW,
  "caleb:science": calebScienceLW,
  "clara:english": claraEnglishLW,
  "david-lim:english": davidLimEnglishLW,
  "david-lim:math": davidLimMathLW,
  "david-lim:science": davidLimScienceLW,
  "drewie:science": drewieScienceLW,
  "eg:english": egEnglishLW,
  "el44:english": el44EnglishLW,
  "elijah:science": elijahScienceLW,
  "emily-lim:english": emilyLimEnglishLW,
  "emily-lim:math": emilyLimMathLW,
  "emily-lim:science": emilyLimScienceLW,
  "enxin:science": enxinScienceLW,
  "evang:math": evangMathLW,
  "fightingseo:math": fightingseoMathLW,
  "hongjun23:science": hongjun23ScienceLW,
  "hooper:math": hooperMathLW,
  "ij:english": ijEnglishLW,
  "ij:science": ijScienceLW,
  "jayron-loh-yi-heng-students-edu-sg:math": jayronLohYiHengStudentsEduSgMathLW,
  "jeremiahsy:english": jeremiahsyEnglishLW,
  "jeremiahsy:math": jeremiahsyMathLW,
  "jeremiahsy:science": jeremiahsyScienceLW,
  "jeron16:english": jeron16EnglishLW,
  "jon-tan:english": jonTanEnglishLW,
  "jon-tan:math": jonTanMathLW,
  "joylynn:english": joylynnEnglishLW,
  "kaiyangnggg:english": kaiyangngggEnglishLW,
  "kaiyangnggg:math": kaiyangngggMathLW,
  "kaiyangnggg:science": kaiyangngggScienceLW,
  "kayden:english": kaydenEnglishLW,
  "lohxy2014:english": lohxy2014EnglishLW,
  "lohxy2014:math": lohxy2014MathLW,
  "lohzr-p4:english": lohzrP4EnglishLW,
  "lohzr-p4:science": lohzrP4ScienceLW,
  "mahdi12:english": mahdi12EnglishLW,
  "mark-lim:english": markLimEnglishLW,
  "mark-lim:math": markLimMathLW,
  "mark-lim:science": markLimScienceLW,
  "meryll:english": meryllEnglishLW,
  "natashatsai:english": natashatsaiEnglishLW,
  "naurahumaira:english": naurahumairaEnglishLW,
  "rizqi:english": rizqiEnglishLW,
  "ruthie:science": ruthieScienceLW,
  "saarah1:english": saarah1EnglishLW,
  "shadow-demon:english": shadowDemonEnglishLW,
  "shayane:english": shayaneEnglishLW,
  "shayane:science": shayaneScienceLW,
  "student66666:english": student66666EnglishLW,
  "tylerng:english": tylerngEnglishLW,
  "tylerng:math": tylerngMathLW,
  "umarh:science": umarhScienceLW,
  "umarm:english": umarmEnglishLW,
};
