import MarketingNav from "@/components/MarketingNav";
import TutorialDetails from "@/components/TutorialDetails";

type FaqSection = { heading: string; items: { q: string; a: string }[] };

type Tutorial = { id: string; title: string; description?: string; videoSrc: string };

const tutorials: Tutorial[] = [
  {
    id: "assigning-first-quiz",
    title: "Assigning your first quiz",
    description: "A 30-second walkthrough of creating a child profile and sending their first quiz.",
    videoSrc: "/tutorials/assigning-first-quiz.mp4",
  },
];

const faqSections: FaqSection[] = [
  {
    heading: "General Questions",
    items: [
      {
        q: "What is MarkForYou?",
        a: "MarkForYou is an AI-powered study assistant designed for parents of primary school students in Singapore. Our platform allows you to assign practices or past-year papers that our AI marks instantly\u2014even handwritten open-ended answers. The AI will identify weak areas and recommend focused practices. We handle the heavy lifting so you can focus on coaching and bridging learning gaps.",
      },
      {
        q: "What subjects and levels are covered?",
        a: "We currently support Primary 4 to 6 English, Mathematics, Science and Chinese, all strictly aligned with the latest MOE syllabus.",
      },
      {
        q: "How do I get started?",
        a: "It\u2019s easy! Sign up as a parent, create a profile for your child, and generate your first quiz in under 2 minutes. No credit card is required.",
      },
      {
        q: "How much does it cost?",
        a: "MarkForYou is currently FREE during our beta period. Our priority is ensuring the best experience for families before we introduce pricing.",
      },
    ],
  },
  {
    heading: "The Learning Experience",
    items: [
      {
        q: "How does the AI marking work?",
        a: "Students complete quizzes directly on their device or on printed worksheets. Our AI is trained to read handwriting, understand MOE scoring rubrics, and marks within seconds.",
      },
      {
        q: "Is the AI marking accurate?",
        a: "Yes, our AI achieves high accuracy across all question types. It is programmed to recognize alternative solutions as long as they align with MOE scoring rubrics. For peace of mind, parents can always review and manually adjust marks on the review page.",
      },
      {
        q: "Where do the questions come from?",
        a: "Our question bank is a curated mix of top-school past-year papers and questions generated by expert AI trained on these papers. We are constantly expanding our database to ensure high-quality, original content.",
      },
      {
        q: "How difficult are the questions?",
        a: "We peg our difficulty level to top-school standards. All questions\u2014whether from past papers or expert-generated\u2014are rigorously checked for syllabus relevancy.",
      },
      {
        q: "Can my child practice specific weak topics?",
        a: "Definitely. Our \u201cFocused Practice\u201d feature allows you to generate a 10+ questions drill on any specific topic. Additionally, our system automatically tracks performance to help you identify which areas need more attention.",
      },
    ],
  },
  {
    heading: "Technical & Troubleshooting",
    items: [
      {
        q: "What if a question covers a topic my child hasn\u2019t learned yet?",
        a: "While we align questions to the typical MOE workplan (e.g., WA1, WA2), schools may teach modules in a different order. If a concept is unfamiliar, simply use the \u201cSkip\u201d function. The score will adjust automatically, and you can see which topics were skipped in the review.",
      },
      {
        q: "I found a mistake in a question or answer. What should I do?",
        a: "We strive for perfection, but if you spot an error, both parents and students can use the \u201cFlag\u201d button. Our team reviews every flagged item to make the necessary corrections.",
      },
      {
        q: "What is the Spelling / \u542C\u5199 function?",
        a: "This feature allows you to scan any spelling list. The AI generates a digital practice session with meanings, examples, and Pinyin. It allows students to test themselves independently, saving parents time.",
      },
      {
        q: "Does my child need a specific device?",
        a: "Any device with a web browser (phone, tablet, or laptop) works. While a tablet with a stylus offers the best experience for handwriting, using a finger on a smartphone works perfectly fine too.",
      },
      {
        q: "How is my child\u2019s data protected?",
        a: "Privacy is our priority. Your child\u2019s data is only accessible via your linked parent account. We never sell personal information to third parties.",
      },
    ],
  },
];

export default function FAQPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#eff6ff] to-white">
      <MarketingNav />

      {/* Content. pt-24/pt-28 so the first heading clears the fixed nav. */}
      <main className="max-w-3xl mx-auto px-6 pt-24 lg:pt-28 pb-10 lg:pb-16">
        <div className="text-center mb-10 lg:mb-14">
          <h1 className="font-headline text-3xl lg:text-4xl font-extrabold text-[#001e40] mb-3">
            Frequently Asked Questions
          </h1>
          <p className="text-lg text-[#43474f]">Everything you need to know about MarkForYou</p>
        </div>

        <div className="space-y-10">
          <div>
            <h2 className="font-headline text-xl lg:text-2xl font-extrabold text-[#001e40] mb-4">Tutorials</h2>
            <div className="space-y-3">
              {tutorials.map((t) => (
                <TutorialDetails key={t.id} id={t.id} title={t.title} description={t.description} videoSrc={t.videoSrc} />
              ))}
            </div>
          </div>
          {faqSections.map((section, si) => (
            <div key={si}>
              <h2 className="font-headline text-xl lg:text-2xl font-extrabold text-[#001e40] mb-4">{section.heading}</h2>
              <div className="space-y-3">
                {section.items.map((faq, i) => (
                  <details key={i} className="group bg-white rounded-2xl border border-[#e5eeff] shadow-sm">
                    <summary className="flex items-center justify-between gap-4 px-6 py-5 cursor-pointer list-none font-headline text-base lg:text-lg font-bold text-[#001e40] hover:text-[#003366] transition-colors">
                      {faq.q}
                      <span className="material-symbols-outlined text-[#43474f] group-open:rotate-180 transition-transform shrink-0">expand_more</span>
                    </summary>
                    <div className="px-6 pb-5 -mt-1">
                      <p className="text-[#43474f] leading-relaxed">{faq.a}</p>
                    </div>
                  </details>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* CTA */}
        <div className="mt-12 text-center">
          <p className="text-[#43474f] mb-4">Still have questions?</p>
          <a href="mailto:peter.lzy@gmail.com" className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#003366] text-white font-bold hover:bg-[#001e40] transition-colors">
            <span className="material-symbols-outlined text-lg">mail</span>
            Contact Us
          </a>
        </div>
      </main>
    </div>
  );
}
